### ISSUE TITLE
Configuration improvements

### ISSUE THREAD

**Issue by Gadsee** [Kyrluckechuck/TFT-Bot#101]
I want to propose making the following changes to the configuration:

1. Move from `.ini` to `.yaml.` YAML is the most user-friendly way to configure things.
2. Create the file if it does not exist.
3. Make more things configurable, such as timeouts, wanted traits, and maybe even the log level.

Open to more suggestions/feedback!
Please note that this is a low-priority suggestion, a great candidate for `do when I want to do something but don't have anything to do` 😛

**Comment by Kyrluckechuck** [comment]
1- No complaints there, I went with `ini` since it was the most common for Python packages but am very open to changing it

2- Sure, though the downside to that is if we change defaults in the future but have written it already, it becomes a bit more complex 😛 Maybe we create the file but don't write any configs unless we have a way to save that in the future?

3- Yep, I love this idea, but I think that would likely warrant individual PRs / feature requests! 🤔
