### ISSUE TITLE
help me QQ  cant work

### ISSUE THREAD

**Issue by qa960362** [Kyrluckechuck/TFT-Bot#138]
[tft-bot-debug-2023-04-14_22-04-35_488519.log](https://github.com/Kyrluckechuck/TFT-Bot/files/11233785/tft-bot-debug-2023-04-14_22-04-35_488519.log)

**Comment by Kyrluckechuck** [comment]
Hello!

Please update the Issue title & post to provide some basic information such a summary of:
- What is happening?
- What is expected?
- Other information such as the League of Legends client/game language 

Without these details it's hard to provide support as your logs don't indicate any issues.

**Comment by Gadsee** [comment]
I assume the league game resolution is not correct, or their window is obstructed by something since we can see the following repeating the entire time:
```
2023-04-14 22:06:06.689 | DEBUG    | __main__:determine_minimum_round:557 - Could not determine minimum round, returning 0.
2023-04-14 22:06:06.827 | DEBUG    | __main__:check_if_gold_at_least:514 - Looking for at least 1 gold
2023-04-14 22:06:07.865 | DEBUG    | __main__:check_if_gold_at_least:522 - No gold value found, assuming we have more
```
(Granted, this is only 3 minutes worth of output, so this could also be "normal behavior" if the game load logic somehow messed up.)

So yeah, I'd also like to know your in-game resolution, if you have multiple monitors, and on which monitor the game is running.

**Comment by qa960362** [comment]
What is happening? 2023-04-14 22:06:06.689 | DEBUG    | __main__:determine_minimum_round:557 - Could not determine minimum round, returning 0.
2023-04-14 22:06:06.827 | DEBUG    | __main__:check_if_gold_at_least:514 - Looking for at least 1 gold
2023-04-14 22:06:07.865 | DEBUG    | __main__:check_if_gold_at_least:522 - No gold value found, assuming we have more

 language chinese  or  english

**Comment by Kyrluckechuck** [comment]
So that doesn't help us any more than the info we already had, but I'll ask a different question, could we get a screenshot of what the game client is showing when you get that error determining round?

The game client would have to be set to English, FYI, unless you want to recapture all of the screenshots we're using for visual matching yourself (which you're welcome to do, of course!)

**Comment by qa960362** [comment]
tested
Dual screens set the main screen, the mouse will always click the lower right corner

Works from a single screen

**Comment by Kyrluckechuck** [comment]
Ah, so this is an issue with multi-monitor support -- [there is already an issue for that](https://github.com/Kyrluckechuck/TFT-Bot/issues/97), so going to close this to avoid duplicates

If you can provide extra information about your dual monitor setup in that issue, that would help. Things like which monitor is the primary (left or right), are both monitors the same resolution, etc.
