### ISSUE TITLE
Pick Up Item Orbs And Equip Champions With Items

### ISSUE THREAD

**Issue by Rigaln** [Kyrluckechuck/TFT-Bot#159]
I would like to have the ability to pick up equipment dropped in the field.
I would like to see the equipment in the lower left corner of the screen be randomized so that the characters can equip it.

If you don't equip them, the possibility of being suspected as a bot will increase, so please implement it!

**Comment by Rigaln** [comment]
I translated it in deepl, so sorry if something is wrong.

**Comment by Kyrluckechuck** [comment]
Thanks for the suggestion here -- while we are not actively working on this feature (not to say we won't in the future), if anyone in the community would like to take a stab at it, we would more than welcome the Pull Request 😄

**Comment by Gadsee** [comment]
I planned to work on this, but the issue is that this is more complex than it might seem at first glance. 

The "dumb" solution would be to drag from the pixels where the items are to estimates of the auto-positioned units on the boards. That would work fine to consider this ticket closed if anyone wants to do it.

The actual and more long-term solution I'd like to see implemented is that we track 
1. Where are our units, and how many units do we have
    a. Super long-term, but probably not as part of this implementation step, which units exactly do we have on the board
2. How many items do we have on the bench at the moment
    a. Long-term, which items exactly do we have
3. Which units have how many items equipped
    a. Differentiate components from items

Altogether, this would form a system to drag specific items to specific champions at positions on the board.

If no one picks this up by the time I'm done farming the MSI pass, I'll slowly work on the individual systems and PR accordingly.
