### ISSUE TITLE
Exe Releases Are Not Available

### ISSUE THREAD

**Issue by PoGOK66** [Kyrluckechuck/TFT-Bot#184]
where is the .exe i can't download it

**Comment by Kyrluckechuck** [comment]
@PoGOK66 please see this note in the `README.md` / on the home page:
> ⚠️ WARNING Users have been reporting an uptick in bans while utilizing TFT botting software. Users of this repo appear to have all been related to using the executable releases, and as such we are removing the uploaded executables from future releases. It is strongly advised against building them yourselves or using older releases, at this time. We can not currently verify if there are source-code users being banned as well, and until we hear otherwise, would recommend users stick to running the python/source method only. Checkpoints / times that users should update their local git copy will be noted with 'releases' in the same consistentcy as before, just without the executables to be downloaded.

After further debugging by @akshualy, we believe the reason for the uptick in bans was actually due to either the way the executable worked, or it was just the fact it was being executed from an executable.

For the time being, the bot works as expected, you just need to follow the [Installation (For Source)](https://github.com/Kyrluckechuck/TFT-Bot#installation-for-source) steps
