### ISSUE TITLE
Mouse doesn't move

### ISSUE THREAD

**Issue by xChickens** [Kyrluckechuck/tft-bot#19]
I don't know why (I've been trying to figure for the past two hours) but my mouse doesn't move. The cursor will just blink like it should move, but it doesn't actually move. 

I tested Detergent's bot it works still to move the mouse.

**Comment by Kyrluckechuck** [comment]
Ahhh, this was related to some changes I made last night with the linting but unfortunately had an inadvertent negative effect -- I resolved it with https://github.com/Kyrluckechuck/tft-bot/commit/eabc3405a64e72a33382fbfb799ddc7197aba23d (but also forgot to create a PR for it since I was rushing) -- pulling latest `main` should resolve it!

Please feel free to reopen this if you are still encountering it, but please include the `tft.log` file if so!

**Comment by xChickens** [comment]
It works! Thanks for the quick fix lol.

I was literally so delirious last night because I thought I was having an issue with my Python installations (I was as well). My issue request has awful grammar.
