### ISSUE TITLE
Script doesn't do anything in game, but alt tabbed works

### ISSUE THREAD

**Issue by Kiure** [Kyrluckechuck/TFT-Bot#221]
Like the title mentioned, it doesn't do anything in-game but works fine when it's alt tabbed, the mouse will automatically move when alt tabbed.

[tft-bot-debug-2023-11-18_00-55-35_636915.log](https://github.com/Kyrluckechuck/TFT-Bot/files/13399163/tft-bot-debug-2023-11-18_00-55-35_636915.log)

I noticed this part in the log

`2023-11-18 00:55:47.378 | DEBUG    | tft_bot.helpers.system_helpers:bring_window_to_forefront:55 - Failed to click to (5, 'BringWindowToTop', 'Access is denied.')`

I tried turning off all my overlay and programs, changing the resolution to 1920x1080 in-game resolution and my monitor, turning off my other monitor. Running with command prompt as admin as well. Just can't seem to get it to work.

**Comment by akshualy** [comment]
Hey, that debug/error message is probably because you're running your League of Legends with Administrator privileges, while the bot/python is running as a normal user. Try running League without and see if the issue persists please :)
I know you said running the command prompt as admin isn't fixing it either, but I'm actually not sure if the terminal is what determines at which privileges the python script executes.

There is also this
`We tried to check League of Legends (TM) Client for an image, but there is no window`
which definitely indicates issues in getting access to the League window.

**Comment by Kiure** [comment]
Ok I seem to be able to get it working by running both League and the command prompt running as admin but I have been using TFT OCR instead because of their comp feature.

Thanks though!
