### ISSUE TITLE
NOT AN ISSUE

### ISSUE THREAD

**Issue by idlesct** [Kyrluckechuck/TFT-Bot#222]
hey, i've been using the bot for a while and the set just newly updated to set 10 with entirely new traits except for bruiser. i'm wondering if there's any way for us to add them to the bot or they'll be added to captures later, since this is a newer set? i'm not too good with coding/scripts so i do apologize if it's a simple issue, i just want to farm the pass tokens w/o placing 8th every game b/c the bot can't lock onto any trait outside bruiser.

**Comment by Kyrluckechuck** [comment]
Thanks for the reminder about Set 10 -- I have a PR up at #223 which will add support for Set 10. You can check that branch out locally for the time being until that is merged if you want it to start working immediately, but it may require a few more minor changes (which is why it hasn't been merged yet)

**Comment by idlesct** [comment]
Hi, thanks for implementing the set 10 traits! Keep up the good work and thanks again for the quick response <3
