### ISSUE TITLE
Set 11

### ISSUE THREAD

**Issue by TogataMirioA2** [Kyrluckechuck/TFT-Bot#246]
hello sir.. a new tft set has released and was wondering if u r gonna update the bot

**Comment by Kyrluckechuck** [comment]
Hey @TogataMirioA2 !

I've actually been thinking about this over the last couple months, and while I'm not certain yet, I'm leaning towards deprecating and archiving this project unless others are wanting to step up!

For the same reasons the upstream fork of the project are considering either shutting it down or porting the bot to work via Bluestacks/another emulator (ideally not Bluestacks IMO tbh) (see this thread for details https://github.com/Detergent13/tft-bot/issues/140).

@akshualy have you had any thoughts on this matter, since you were the other core contributor?
Unfortunately if we were to port it to operating on TFT mobile, we'd like have to revert a number of the changes where we were making use of the League API's and instead need to transition it to be screen-based only 😞

**Comment by TogataMirioA2** [comment]
i appreciate ur response and that would be a great idea to settle this vanguard thing down. the official vanguard wiki site says it ll be released in april there is enough time to do such a thing which secretly i hope u to do so cos i ve no time to play but still wanna get these skins so badly

**Comment by kalmaguer** [comment]
@TogataMirioA2 Detergent13 updated his for set 11 by adding invoker and dragonlord, so you can probably just grab his pngs, update contestants.py, and then you'll be good to go for the rest of this 4 week event or until vanguard comes out.

**Comment by TogataMirioA2** [comment]
@kalmaguer i ll try

**Comment by TogataMirioA2** [comment]
@kalmaguer detergent13 bot has no files to be copied or transferred. cant find the config.yaml or constants.py in his bot files

**Comment by akshualy** [comment]
> porting the bot to work via Bluestacks/another emulator
I've actually been thinking about this as well funnily enough, without knowing of the upstream repository's plans.
It won't be a solution for me personally, due to event pass progress not being counted if you play mobile TFT (as far as I know, please correct me if I'm wrong!).

We'll have to wait and see what Vanguard does. They keep delaying the test release in the phillipines, and I'd be down to continue updating at least some of the traits for the sets until it's 100% confirmed that Vanguard will terminate normal TFT matches/prevent us from executing python.

I wanted to update for the High Noon pass as well, I'll PR something soon :)

**Comment by Detergent13** [comment]
> > porting the bot to work via Bluestacks/another emulator
> 
> I've actually been thinking about this as well funnily enough, without knowing of the upstream repository's plans. It won't be a solution for me personally, due to event pass progress not being counted if you play mobile TFT (as far as I know, please correct me if I'm wrong!).
> 
> We'll have to wait and see what Vanguard does. They keep delaying the test release in the phillipines, and I'd be down to continue updating at least some of the traits for the sets until it's 100% confirmed that Vanguard will terminate normal TFT matches/prevent us from executing python.
> 
> I wanted to update for the High Noon pass as well, I'll PR something soon :)

Didn't consider that mobile games might not count for progress! I haven't tested either way, but definitely throws a wrench in my plans if so.

**Comment by TogataMirioA2** [comment]
@Detergent13 @akshualy actually playing tft on mobile grants you tokens as well.. the two platforms are synced in progress but u cant use ur tokens on mobile though.. a well known technique to farm tokens on mobile is to play in a semi afk fashion it allows u to get tokens when u r away from ur pc.. u can do a final check urself before working on that emulator bot

**Comment by akshualy** [comment]
@TogataMirioA2 I just did a test, you're correct! Thanks for that info :)
I have some experience in mobile game automation through emulators, if either @Detergent13 and or @Kyrluckechuck want to, we can talk out details in some discussion thread or on Discord?

**Comment by TogataMirioA2** [comment]
@akshualy i am the one who wanna thank u for making such a thing real

**Comment by Kyrluckechuck** [comment]
@akshualy that's definitely of interest to me -- if we can bypass the PC portion of Vanguard and/or process listing (which it currently does), that's typically been my main concern for the last year or so.

**Comment by Detergent13** [comment]
I'm pretty busy for the next week or so, but would definitely be happy to sit down and hash out some ideas with you all. Maybe the opportunity to finally merge both bots together?

**Comment by akshualy** [comment]
I created an [organization](https://github.com/TeamFightTacticsBots) and invited both of you :) I'd prefer discussions over Discord (my tag is `akshualy`), but if either of you doesn't want to use that, I'll create a discussion holding repository in that organization.

**Comment by Detergent13** [comment]
Added you :)
