### ISSUE TITLE
League client not detected, restarting loop

### ISSUE THREAD

**Issue by UnjerkedChicken1999** [Kyrluckechuck/TFT-Bot#43]
Starts and then terminates League client indefinitely. Using latest release and python 3.10.8, League is located at C:\Riot Games\League of Legends

[TFT.Bot.log](https://github.com/Kyrluckechuck/TFT-Bot/files/10201193/TFT.Bot.log)

**Comment by Kyrluckechuck** [comment]
That is odd, it is detecting the path to be `C:/Riot Games/League of Legends` instead of `C:\Riot Games\League of Legends`.

Would you be able to check the registry key `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Riot Game league_of_legends.live` for the value `InstallLocation` and confirm that value is `C:\Riot Games\League of Legends` as it should be? If it's not, I will have to do a conversion of some sort to avoid this, but it's odd it doesn't always install it with that path..

**Comment by UnjerkedChicken1999** [comment]
![InstallLocation](https://user-images.githubusercontent.com/120285752/207095222-bdcdee6c-34b3-47b3-be8c-5288ebb93421.PNG)

This is what it says.

**Comment by Kyrluckechuck** [comment]
Very odd, okay, I add this in a followup PR to convert these file paths

**Comment by Kyrluckechuck** [comment]
Included in [Release v0.9.7](https://github.com/Kyrluckechuck/TFT-Bot/releases/tag/main-54c0a24b)
