### ISSUE TITLE
Doesnt find/ accept game

### ISSUE THREAD

**Issue by Kiruscha** [Kyrluckechuck/TFT-Bot#63]
For whatever reason the bot plays one game and then fails to go into the next game.
Not sure if it fails at accepting or finding a match.

Anyone else got that issue?

**Comment by Kyrluckechuck** [comment]
Hello!

Could you let me know some things about this?
- What version are you running (if a release), or what commit are you running (if it's git cloned)?
- Could you provide the log file from a time you ran it where this behaviour was shown?

I do know this was an issue with 0.9.11 & 0.9.12 due to some changes by Riot with the last update, but [0.9.13](https://github.com/Kyrluckechuck/TFT-Bot/releases/tag/main-30f190f7) resolved that. I just ran that version for 36 hours straight and it had no issues getting stuck.

**Comment by Kyrluckechuck** [comment]
I'm going to go ahead and close this for now since it doesn't seem to be a current bug and there was no response.

Please feel free to re-open this if there is more to discuss.
