### ISSUE TITLE
The bot didn't queue up from the start and after the game end

### ISSUE THREAD

**Issue by hazedj** [Kyrluckechuck/TFT-Bot#81]
And is the bot suppose to just always click lvl up like that? 
I'm using the source version with 1280x720 client and 1920x1080 window borderless 
Or is it because i use Thai language for league, should i change it?

**Comment by Kyrluckechuck** [comment]
I'm not sure what you are actually reporting here, do you have any logs and/or screenshots of what you're describing?

>  I'm using the source version with 1280x720 client and 1920x1080 window borderless

That sounds right, fullscreen vs borderless shouldn't matter

>  Or is it because i use Thai language for league, should i change it?

That's possible, any screenshots which do text matching will fail because they are looking for text matches, and the screenshots are only recorded in English. You're welcome to replace the screenshots in your local folder if you'd like, but I will warn you that it will be a maintenance burden to re-record them every time I add more, etc, and becomes harder for me to support you. If you're able to change your client language, you will likely have a better experience with the bot!

> And is the bot suppose to just always click lvl up like that?

Yes, the bot prioritizes leveling up over re-rolls and champion purchases since in my experience with the bot without implementing much more complicated decision tree logic, this is the highest chance of getting the bot to the top 4 (which increases the amount of event XP earned per match).

**Comment by Kyrluckechuck** [comment]
Hey there, just wanted to check if this is still an issue after switching the League client language to English / recording over each of the needed images locally?

**Comment by Gadsee** [comment]
Closing this as the bot is mostly language-agnostic now. Friendly reminder that a new pass is starting in 7 hours.
